dist: trusty
sudo: false
language: node_js
node_js:
- '9'
os:
- linux
cache: yarn
env:
- FIREFOX_VERSION="latest"
- FIREFOX_VERSION="59.0.2"
before_install:
- echo $FIREFOX_VERSION
- export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-'$FIREFOX_VERSION'&lang=en-US&os=linux64'
- wget --no-verbose -O /tmp/firefox-$FIREFOX_VERSION.tar.bz2 $FIREFOX_SOURCE_URL
- mkdir /tmp/firefox-$FIREFOX_VERSION
- tar -xvf /tmp/firefox-$FIREFOX_VERSION.tar.bz2 -C /tmp/firefox-$FIREFOX_VERSION
- export PATH=/tmp/firefox-$FIREFOX_VERSION/firefox:$PATH
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export CHROME_BIN=/usr/bin/google-chrome
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation google-chrome-stable
install:
- yarn install
script:
- firefox --version
- npm run lint
- npm run test:once
- npm run e2e
after_success:
- npm run packagr
before_deploy:
- touch .npmignore
- cd dist/
deploy:
  skip_cleanup: true
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: "qWz0j304DHYLvHlsCwBnihKx182/lHxjWmIWr1UOeV74DOKF7ChmQXG+thVLAn+HiyveQkJxMqSJPEfokluWNum9cpLl+v3EZu9lkoVAfe3wknL9VUNdsvTVgL2fnjuEPeFKif+HHCuyFmTX7ZR5Zy9uv4OhjTwgKaw5Zvwdh04AknEsG4yhAZ/rmECVuCs62JgNeCt6oEPe5Nxfp2USRHG/gIdMKhArCevZL2f1SYEl7h1xdOeAW6+vFFf3VsgUgduNMOj8Us76c7grlMF9u3EJcxgzmfUTF7OyECQj+ZxwXVr6S7R4k8+Facw9D6niGzCc/ydEtxzSbC7vUlGGKKU0XYLNHnNtnfJGj5LLwUk4habdtXhxw7Jf8asgszseJCOdB1eepWb1RuUnwat0DrpKbzq+KITFwfHOQm/zZq6xRETLnht3voS15BDjG+VjXmpODPwiv6fqpl3uTfpgZI6aYSuyh8Umz+diOHkQjKYGV5kr5s/Xz7bA3sYvJTlYdD8fPFz9cPW1PIBqosATw6Ng8IB7LO9AwUHfC9NWka/JpsbnkeKTHMQuwjPh88QDg+tFu8cL1wi4Cft8IW1uM6zvgxCE1+JfjfdvRZ5/+3YyiBwhncNZObJbOc0mg23zDtUwoJDeM84WmXZX7ula98HW7Zz/sHJyZgKum70eixU="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-testeditor-commons
