dist: trusty
sudo: false
language: node_js
node_js:
- '9'
os:
- linux
cache: yarn
env:
- FIREFOX_VERSION="latest"
- FIREFOX_VERSION="59.0.2"
before_install:
- echo $FIREFOX_VERSION
- export FIREFOX_SOURCE_URL='https://download.mozilla.org/?product=firefox-'$FIREFOX_VERSION'&lang=en-US&os=linux64'
- wget --no-verbose -O /tmp/firefox-$FIREFOX_VERSION.tar.bz2 $FIREFOX_SOURCE_URL
- mkdir /tmp/firefox-$FIREFOX_VERSION
- tar -xvf /tmp/firefox-$FIREFOX_VERSION.tar.bz2 -C /tmp/firefox-$FIREFOX_VERSION
- export PATH=/tmp/firefox-$FIREFOX_VERSION/firefox:$PATH
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- export CHROME_BIN=/usr/bin/google-chrome
- curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.6.0
- export PATH="$HOME/.yarn/bin:$PATH"
- sudo apt-get update
- sudo apt-get install -y libappindicator1 fonts-liberation google-chrome-stable
install:
- yarn install
script:
- firefox --version
- npm run lint
- npm run test:once
- npm run e2e
after_success:
- npm run packagr
# Autoincrement of patch level version:
# Tag the repo with a new patch level version tag, if this build is done on
#     'FIREFOX_VERSION = latest' and (only one of the matrix-builds is relevant)
#     this is not a pull request and (pull requests themselves should not autoincrement)
#     this branch is the master branch and (only builds on master are relevant)
#     there is no tag given (if a tag is alread given, this one will be published and should not again be tagged!)
- 'if [ "$FIREFOX_VERSION" = "latest" -a "$TRAVIS_PULL_REQUEST" = "false" -a "$TRAVIS_BRANCH" = "master" -a "$TRAVIS_TAG" = "" ]; then wget https://github.com/test-editor/commons-build-automation/raw/master/travis/deploy/tag_with_new_patch_version.sh; bash tag_with_new_patch_version.sh; fi'
before_deploy:
- touch .npmignore
- cd dist/
deploy:
  skip_cleanup: true
  provider: npm
  email: service.eng@akquinet.de
  api_key:
    secure: "sfAhZgj8wDuBVtD5Ly7lBgcs5k7j2jGYWYVmjURZBwBHdFzwvqT/L0HWoq0w+GyljuJu47uXlDOhsQEGmyJnS58NofoAI9qBfUwuJwIdQmfulsLXyvyof+JPbF87bequrEVsUSujWHwaLaSjHgFGHgkj3B3XcoR0uLhQDPGZqNFsDbL8FH5tjyr6LDLjCm675+wVqBynvC+nR5K4XTLNRq8oWOrFAanayc41yBTTq6xhra1+2XWu1N5tiLweERARA7WjrgbX7FshPROlpAsIuvmaVbdaIhuEn6aBzfQni74EMPf4TXLqCCD+i+nZyq9A6DEqQHN418mMxwVOHISMJzYvRAY5Bvz+4RlMRy5vjyE03KR26J8yDNlA2GGwTyXxvSmzBz3TK8RkrkJF5hNadI768rf2mS+2Iyhj3CHIbBJnMyKjeYlZ8Qae9AvDFwNX73dAdOIjyoAUGDCsuVqTFXaL0MLPNQmZg0oR6wcRBmqz43njhiUheq5NFecBrmTIBKB+8VN6OUqCzekMXU6E4oOZbjxPXYvqeyssz6iIQNKW+bMHqwkJVtq1CFdXvkb2RhHz4KY35FONix4axsxRpr53X1+C32iK11joNy6NDvn/u4KvTuQoCQqNLYNWCIiUss6Wtj4uf5y6V3dejfW/Vv9qXIokPZ6u4kACGGjUO+U="
  on:
    condition: "$FIREFOX_VERSION = latest"
    tags: true
    repo: test-editor/web-testeditor-commons
